trigger:
- master

jobs:
- job: 'Test'
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
    maxParallel: 4

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: python -m pip install --quiet --upgrade pip && pip install --quiet --requirement requirements.txt
    displayName: 'Requirements (Stage 1)'

  - script: |
      flake8 --ignore=E501,E231
      pylint --errors-only --disable=C0301 --disable=C0326 *.py tests/*.py
      python -m unittest --verbose --failfast
    displayName: 'Check (Stage 2)'

- job: 'Staging'
  pool:
    vmImage: 'Ubuntu-16.04'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
    maxParallel: 4

  variables:
  - group: AWS Credentials

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'

  - script: |
      python -m pip install --quiet --upgrade pip && pip install --quiet --requirement requirements.txt
      echo ./upload-new-version.sh
    displayName: 'Build (Stage 3)'

  - script: echo ./deploy-new-version.sh staging
    displayName: 'Deploy Staging (Stage 4)'

  - script: ./test-environment.sh staging
    displayName: 'Test Staging (Stage 5)'
